DELETE http://localhost:3001/api/persons/1
Content-Type: application/json

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Hello World",
  "number": "123-456789"
}