POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test New blog",
    "author": "John Mik",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 0
}